### ISSUE TITLE
Package Upgrade issue

### ISSUE THREAD

**Issue by YDA93** [ukasz123/soundpool#115]
```
Because soundpool >=2.3.0 depends on soundpool_web ^2.2.0 which depends on http ^0.13.0, soundpool >=2.3.0 requires http ^0.13.0.
And because google_fonts >=4.0.5 depends on http ^1.0.0, soundpool >=2.3.0 is incompatible with google_fonts >=4.0.5.
So, because fecare depends on both google_fonts ^5.0.0 and soundpool ^2.3.0, version solving failed.
```

**Comment by MrCsabaToth** [comment]
This is dragging, @ukasz123 please merge and make a new release

**Comment by MrCsabaToth** [comment]
Since my app is mobile only and I don't rely on web platform, I can totally rely on a workaround I already had to use for the wakelock plugin (that case it was the win32 dependency, which is also irrelevant to me but blocked my version bumps): add this to your app's pubspec.yaml before your `dependencies:`:
```
dependency_overrides:
  http: 1.1.0

dependencies:
  ...
```

**Comment by yelkamel** [comment]
I have the same issue
