### ISSUE TITLE
Feature: Playback rate

### ISSUE THREAD

**Issue by YohanWadia** [ukasz123/soundpool#22]
In the real Android sound pool we have 1 very important parameter i.e float rate to modify the pitch of the sound...
See this, it is the last argument:
play(int soundID, float leftVolume, float rightVolume, int priority, int loop, float rate)...

Does this flutter package have anything like that?
How may I handle such modification with your package... like we could in basic Android with Java?

**Comment by ukasz123** [comment]
It does not currently. But it should be possible to add this feature.

**Comment by YohanWadia** [comment]
Brilliant.... I think its really important. Do consider every game uses this feature for falling, acceleration, bullet passing etc etc
Its also used in loads of animations. Please do consider this as a request.
Thanks.

**Comment by ukasz123** [comment]
Done in version **0.6.1**

**Comment by YohanWadia** [comment]
Great!... give me a bit... will try it out. Thanks again.

**Comment by YohanWadia** [comment]
Works brilliantly... no bugs! 
Wanted to share an example where this SoundPool could be really useful... especially while working with Flame.
Heres the link... You are free to use it to help with widening your example base. In fact pls do.
https://github.com/YohanWadia/SoundPool_Flame.git

Just 1 Question:
in a given situation like that where i extend Game Class... where do I call SoundPool.dispose() to free up the memory. In Android I'd do it in onDestroy. what should be the right way over here? can I do something without adding another external package?

**Comment by ukasz123** [comment]
Probably you'd never need that because Soundpool instances would usually be used as singletons that lasts the whole lifetime of the app.

But if you are creating separate Soundpools for each scenario/chapter of the game then it can be disposed when scenario is completed. But even then it would be better to have a single instance and call `release()` on it - it just unloads sounds but keeps the native pool/cache ready.
