### ISSUE TITLE
Muted when no phone is muted

### ISSUE THREAD

**Issue by killian2k** [ukasz123/soundpool#42]
Hello,
When I try to play a sound on my android phone, the sound is considered not as a media but as a ring. If my phone is in silenced mode it doesn't produce any sound.
Any idea how to solve it? 
thanks.

**Comment by SmashHighlights** [comment]
I have the same issue on iOS, and it's also mentioned here: https://github.com/ukasz123/soundpool/issues/28

If the device is on silent, then no sound is played at all; Otherwise, sound is played at the device's media volume as intended.

I hope this can be resolved because soundpool seems to be the best package for low latency audio.

**Comment by ukasz123** [comment]
Sorry for late reply. 
@killian2k First, I'd check the `streamType` parameter of `Soundpool`s constructor.

**Comment by lukepighetti** [comment]
I am also having this issue and was not able to find a `streamType` that allowed playing audio on iOS when the hardware switch is set to silent.
